version: '3.9'

services:
    bbc-iplayer:
        container_name: get_iplayer
        build:
            context: .
            dockerfile: Dockerfile
        image: get_iplayer:latest
        restart: always
        security_opt:
            - no-new-privileges:true
        # networks:
        #     - frontend
        ports:
            - 8181:8181
        volumes:
            - ./iplayer-output:/root/output:rw
            - ./data:/root/.get_iplayer:rw

# networks:
#     frontend:
#         external: true
